language: scala

jdk: openjdk8

scala:
  - 2.12.9
  - 2.13.0

script:
  - sbt compile
  - sbt test

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.8.5
