language: scala
jdk: openjdk8
scala:
- 2.12.9
- 2.13.0
script:
- sbt compile
- sbt test
before_install:
- openssl aes-256-cbc -K $encrypted_1901c275d690_key -iv $encrypted_1901c275d690_iv
  -in .travis/travis-deploy-key.enc -out .travis/travis-deploy-key -d
- export PATH=${PATH}:./vendor/bundle
install:
- rvm use 2.6.0 --install --fuzzy
- gem update --system
- gem install sass
- gem install jekyll -v 3.8.5
